### ISSUE TITLE
Add tests and pipelines

### ISSUE THREAD

**Issue by paragor** [phuslu/nginx-ssl-fingerprint#25]
I think project need some tests in pipeline for production grade.

For example:
1) some popular ja3 hashes
2) http and https smoke tests
3) invalid ssl handshake 
4) something else?

I can write some.

But what language choose? python (with tlsfuzzer library) and go (with ja3transport) is pretty good candidate.

I would rather choose go. What do you think @phuslu  @deancn ?

p.s. golang transport cant use "tls heartbeat", but i think it is ok.

**Comment by deancn** [comment]
I prefer to use go.
 `https://github.com/airdb/ja3transport` has already implemented a few cases.

can add to GitHub action workflow to do the auto testing

**Comment by phuslu** [comment]
Great and thanks, I will try once i have time.

**Comment by phuslu** [comment]
done with github action. thanks anyway.
