### ISSUE TITLE
Any plan to support nginx-quic & quictls-openssl ?

### ISSUE THREAD

**Issue by Zerorigin** [phuslu/nginx-ssl-fingerprint#30]
about [nginx-quic](https://hg.nginx.org/nginx-quic/shortlog/quic)
about [quictls-openssl](https://github.com/quictls/openssl)

**Comment by phuslu** [comment]
I added openssl-3.2 patch , please check it https://github.com/phuslu/nginx-ssl-fingerprint/blob/master/patches/openssl.3_2.patch thanks
