### ISSUE TITLE
HTTP2 fingerprint schema

### ISSUE THREAD

**Issue by arlequin99** [phuslu/nginx-ssl-fingerprint#40]
Most fingerprint schemas use the window_size_increment (http2.window_update.window_size_increment)  field as second parameter:

`[SETTINGS]|WINDOW_UPDATE|PRIORITY|Pseudo-Header-Order|HEADERS_FRAME|WINDOW_UPDATE`

But here the second passed parameter is the http2.settings.initial_window_size

What's the reason for this?

**Comment by phuslu** [comment]
Should be a bug of implementation, thanks! Let me fix it soon. cc @deancn

**Comment by phuslu** [comment]
try fix in https://github.com/phuslu/nginx-ssl-fingerprint/commit/211d8604a3a812413a2c806d0026df467ca781d6

Please help a check, thanks again.

**Comment by arlequin99** [comment]
Thanks. I made some extra tests, what is the value now ? Because it is not WINDOW_UPDATE (http2.window_update.window_size_increment)

![Wireshark_zyVZq62p5V](https://github.com/phuslu/nginx-ssl-fingerprint/assets/19653185/eaecc520-41e1-4be2-a621-af882a94feb6)

**Comment by phuslu** [comment]
sorry for late reply, I try fix in master branch again. Could you please help verify again? thanks a lot!
