### ISSUE TITLE
Hello, I have a question.

### ISSUE THREAD

**Issue by KMG-IDC24** [phuslu/nginx-ssl-fingerprint#41]
Hello, is there a compatible version other than nginx 1.23.1?

**Comment by phuslu** [comment]
good question. In the begging I suppose/believe the nginx.patch is simple enough,
1. it could be apply into common nginx versions
2. Or it could be modified by users then apply their wanted version.

But as more and more users find this project, it's time to split nginx.patch to certain nginx version. Let me do that soon.

**Comment by phuslu** [comment]
done
