### ISSUE TITLE
Support http_ssl_ja3_hash

### ISSUE THREAD

**Issue by cello86** [phuslu/nginx-ssl-fingerprint#44]
Could you check if is it possible to add  http_ssl_ja3_hash function?

Thanks,
Marcello

**Comment by phuslu** [comment]
due to chrome introduces the random extension order in clienthello, the md5 hash of ja3 is less useful. So I deleted in https://github.com/phuslu/nginx-ssl-fingerprint/commit/2ddab697f2e67c94be78bb9fff6924a6439dda0d

**Comment by phuslu** [comment]
ja4 intend to mitigate this change, let us keep eye on it and implement ja4 in time
