### ISSUE TITLE
ERROR: LeakSanitizer: detected memory leaks

### ISSUE THREAD

**Issue by qinyz** [phuslu/nginx-ssl-fingerprint#48]
installed version
openssl-3.2
nginx-1.25.3

Running nginx reports an error

==50858==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1024 byte(s) in 1 object(s) allocated from:
    #0 0x7f836aaa65c0 in posix_memalign (/usr/lib64/libasan.so.4+0xe05c0)
    #1 0x4fdd0e in ngx_memalign src/os/unix/ngx_alloc.c:57
    #2 0x490397 in ngx_create_pool src/core/ngx_palloc.c:23
    #3 0x48ae63 in main src/core/nginx.c:254
    #4 0x7f836a73fb26 in __libc_start_main (/usr/lib64/libc.so.6+0x25b26)

**Comment by phuslu** [comment]
I believe it's duplicated with https://github.com/phuslu/nginx-ssl-fingerprint/issues/34#issuecomment-1407424455
