### ISSUE TITLE
源码包 部署以后 akamai 是空的 ？ 请问是为什么

### ISSUE THREAD

**Issue by meikongli** [phuslu/nginx-ssl-fingerprint#49]
{   "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",   "ja3_hash": "40adfd923eb82b89d8836ba37a19bca1",   "ja3_text": "771,4866-4867-4865-49196-49200-159-52393-52392-52394-49195-49199-158-49188-49192-107-49187-49191-103-49162-49172-57-49161-49171-51-157-156-61-60-53-47-255,0-11-10-35-22-23-13-43-45-51,29-23-30-25-24,0-1-2",   "ja3n_hash": "a4518eeb044cff26ec5f82d0cca28b6d",   "ja3n_text": "771,4866-4867-4865-49196-49200-159-52393-52392-52394-49195-49199-158-49188-49192-107-49187-49191-103-49162-49172-57-49161-49171-51-157-156-61-60-53-47-255,0-10-11-13-22-23-35-43-45-51,29-23-30-25-24,0-1-2",   "akamai_hash": "",   "akamai_text": "" }

**Comment by phuslu** [comment]
看起来这个输出和本项目无关，可能问错地方了。

如果确实是 nginx-ssl-fingerprint 的项目，请补充更多信息并打开这个issue。

**Comment by phuslu** [comment]
我可能明白你的意思了，你是想在 proxy_pass 伪装 nginx 的指纹。

这个项目不是这个作用。
